# Generated by Django 4.1.3 on 2023-01-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdr_core", "0005_alter_rule_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_arr", models.JSONField(null=True)),
            ],
        ),
    ]
